version: "3.9"

volumes:
  pg_volume:

services:

  java_application:
    build: .
    restart: always
    container_name: highload-java
    ports:
    - "8080:8080"
    depends_on:
      - postgresql_database
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://postgresql_database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  postgresql_database:
    image: postgres:15
    container_name: postgresql_databse
    expose:
      - "5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
