version: "3.9"

volumes:
  pg_volume:

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  avito-client:
    build:
      context: .
      dockerfile: avito-client/Dockerfile
    restart: always
    container_name: avito-client
    ports:
      - "8081:8081"
    depends_on:
      - database
      - eureka-server
      - config-server
      - kafka
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  account-server:
    build:
      context: .
      dockerfile: account-server/Dockerfile
    restart: always
    container_name: account-server
    ports:
    - "8082:8082"
    depends_on:
      - database
      - eureka-server
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=r2dbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    restart: always
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - database
      - eureka-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    restart: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - account-server
      - avito-client
      - idp-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka

  idp-server:
    build:
      context: .
      dockerfile: IDP-server/Dockerfile
    restart: always
    container_name: idp-server
    ports:
      - "9000:9000"
    depends_on:
      - database
      - eureka-server
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka

  notification-center:
    build:
      context: .
      dockerfile: notification-center/Dockerfile
    restart: always
    container_name: notification-center
    ports:
      - "9090:9090"
      - "587:587"
    depends_on:
      - database
      - eureka-server
      - config-server
      - kafka
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  file-server:
    build:
      context: .
      dockerfile: file-server/Dockerfile
    restart: always
    container_name: file-server
    ports:
      - "9091:9091"
    depends_on:
      - database
      - eureka-server
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - CONFIG_URL=http://config-server:8888
      - EUREKA_URL=http://eureka-server:8761/eureka


  database:
    image: postgres:15
    container_name: database
    expose:
      - "5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
