server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'systemshighload@gmail.com'
    password: 'njlzsfozqbrgjmjp'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-center
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  config:
    import: configserver:${CONFIG_URL}
  sql:
    init:
      platform: postgres
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
