server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  config:
    import: configserver:${CONFIG_URL}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
