server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  private:
    key: classpath:key
  public:
    key: classpath:key.pub