server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/stmikeal/Highload-System-Config
          clone-on-start: true
