server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  config:
    import: configserver:${CONFIG_URL}
  application:
    name: avito-client
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

jwt:
  private.key: classpath:key
  public.key: classpath:key.pub