name: push eureka-server image to dockerhub

on:
    push:
        paths:
            - eureka-server/**
        branches: [ "master" ]

env:
    SERVICE_NAME: eureka-server

jobs:
    dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}
            - name: Build and Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./${{ env.SERVICE_NAME }}/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ${{ secrets.PROJECT_DIR }}
                      git pull
                      docker container stop $(docker ps -a --format '{{.Names}}' | grep ^${{ env.SERVICE_NAME }})
                      docker container rm $(docker ps -a --filter name=${{ env.SERVICE_NAME }}* -aq)
                      docker image rm highloadsystem_${{ env.SERVICE_NAME }}
                      docker compose up -d ${{ env.SERVICE_NAME }}
#                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}
#                      docker run --network=highperformancesystems_default \
#                        --name ${{ env.SERVICE_NAME }}  -p 8081:8081 -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}