name: run tests

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: | # optional
            account-server/*.gradle*
            avito-client/*.gradle*
            config-server/*.gradle*
            eureka-server/*.gradle*
            file-server/*.gradle*
            gateway/*.gradle*
            IDP-server/*.gradle*
            notification-center/*.gradle*
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test