server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: configserver:${CONFIG_URL}
  application:
    name: idp-server
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
